config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users,  :has_many => :addresses, :controllers => {registrations: 'registrations'}

  resources :users do
  	resources :addresses
  end
  
  resources :tokens 
    
  resources :gyms do
  	resources :addresses
  end
    
    #resources :requests, defaults: { format: 'json' }
    get 'home/index' => 'home#index'

    root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :user
  has_one :gym   
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tokens
  # GET /tokens.json
  def index
    if current_user.regular?
      if Token.where('DATE(created_at) =?', Date.today).where(:user_id => current_user.id).first_or_create!(:code => "TK" + (current_user.id).to_s + 
        Date.today.strftime("%d%m%Y"), :status => true, :user_id => current_user.id)
      end
    end
      @q = Token.ransack(params[:q])     
      @tk = @q.result     
      @tokens_user = Token.all.select{ |t| t.user_id == current_user.id }

    if(current_user.admin?)
      @adminTokens = Token.connection.select_all "SELECT tokens.status, tokens.code, tokens.id, tokens.user_id, tokens.gym_id, gyms.name FROM tokens JOIN gyms on tokens.gym_id = gyms.id;"
    
    end
  end

  def show
    redirect_to(request.referrer || token_path)
  end

  # GET /tokens/1/edit
  def edit
  end
  # PATCH/PUT /tokens/1
  # PATCH/PUT /tokens/1.json
  def update
      if current_user.gympass? || current_user.admin?
        @token.status = false
        if @token.update(token_params)
          flash[:alert] = "Token utilizado com sucesso"
          redirect_to(request.referrer || token_path)
        else
          format.html { render :index }
          format.json { render json: @token.errors, status: :unprocessable_entity }
        end
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = Token.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_params
     params.require(:token).permit(:status, :code, :gym_id, :user_id)
     #params.require(:token).permit!
    end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_admin_index.html.erb
<p id="notice"><%= notice %></p>
<%= search_form_for @q do |t| %>
  <%= t.label :code_eq, "Código do Token" %>
  <%= t.search_field :code_eq %>
  <%= t.submit "Procurar Token" %>
<%end%>

  <h3>Tokens Disponíveis no dia </h3>  
 <table>
  <thead>
    <tr>
      <th>Código</th>
      <th>Usuário</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tk.each do |t| %>
      <tr>
        <% if t.status?%>
          <td><%= t.code %></td>
          <td><%= User.find(t.user_id).name %></td>
          <td>Disponível</td>
          <td><%= link_to 'Validar Token', edit_token_path(t) %></td>
        <%end %>
      </tr>
    <%end %>
  </tbody>
</table>
<br>
<h3>Histórico de Tokens Validados </h3>  
<%if @adminTokens.empty?%>
  <h4>Nenhum token validado</h4>  
<%else%>
  <table>
    <thead>
      <tr>
        <th>Código</th>
        <th>Usuário</th>
        <th>Status</th>
        <th>Academia</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @adminTokens.each do |t| %>
        <tr>
          <td><%= t['code'] %></td>
          <td><%= User.find(t['user_id']).name  %></td>
          <td>Utilizado</td>
          <td><%= t['name']%></td>  
        </tr>
      <%end %>
  </tbody>
</table>
<%end%>

app/views/tokens/_form.html.erb
<%= form_for(token) do |f| %>
<% if token.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(token.errors.count, "error") %> prohibited this token from being saved:</h2>
  <ul>
    <% token.errors.full_messages.each do |message| %>
    <li><%= message %></li>
<% end %>
  </ul>
  </div>
  <% end %>
  <%if current_user.regular?%>
    <div class="actions">
      <%= f.submit "Solicitar token" %>
    </div>
  <%else%>
      <div class="field">
        <%= f.text_field :status, :value => false, :readonly => "readonly", :style => "display:none" %>
        <%= f.text_field :user_id, :readonly => "readonly", :style => "display:none" %>
      </div>
      <div class="field">
        <%= f.label :code, "Código" %>
        <%= f.text_field :code, :readonly => "readonly" %>
      </div>
      <%if !Gym.exists?(user_id: current_user.id) %>
        <h3>O token não pode ser validado, pois o usuário não possui academias cadastradas!</h3>
      <%else%>
          <div class="field">
            <%= f.label :gym_id, "Academia" %>
            <%if current_user.gympass? %>
              <%= f.select :gym_id, Gym.all.select{|t| t.status? }.collect {|x| [x.name, x.id]}, :multiple => true %>
            <%else%>
                <%= f.select :gym_id, Gym.all.select{|t| t.user_id == current_user.id && t.status? }.collect {|x| [x.name, x.id]}, :multiple => true %>
            <%end%>
        <%end%>
        <div class="actions">
          <%= f.submit "Validar token", :id => "validatioButton" %>
          </div>
      <%end%>
  <%end%>

app/views/tokens/_gympass_index.html.erb
<p id="notice"><%= notice %></p>
<%= search_form_for @q do |t| %>
  <%= t.label :code_eq, "Código do Token" %>
  <%= t.search_field :code_eq %>
  <%= t.submit "Procurar Token" %>
<%end%>

  <h3>Tokens Disponíveis no dia </h3>  
 <table>
  <thead>
    <tr>
      <th>Código</th>
      <th>Usuário</th>
      <th>Status</th>
      <th>Academia</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tk.each do |t| %>
      <tr>        
        <td><%= t.code %></td>
        <td><%= User.find(t.user_id).name %></td>
        <% if t.status?%>
          <td>Disponível</td>
          <td><%= link_to 'Validar Token', edit_token_path(t) %></td>
        <%else %>
          <td>Utilizado</td>
        <%end %>
        <td><%= Gym.find(t.gym_id).name %></td>
      </tr>
    <%end %>
  </tbody>
</table>

app/views/tokens/_regular_user_index.html.erb
<h2>Token do Dia</h2>
<% @tokens_user.each do |t| %>
<% if t.status? %>
  <strong><%=t.code%></strong>
  <h3>Valido até às 23h59 de <%= Date.today.strftime("%d/%m/%Y") %></h3>
<%else%>
<h3>Você já utilizou seu token diário!</h3>
<%end%>
<%end%>

<br>
<h1>Histórico Tokens Utilizados</h1>
<table>
  <thead>
    <tr>
      <th>Código</th>
      <th>Status</th>
      <th>Data</th>
      <th>Academia</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @tokens_user.each do |token| %>
    <%if !token.status?%>
    <tr>
      <td><%= token.code %></td>
      <%if !token.status?%>
        <td>Utilizado</td>
      <% end %>
      <td><%= token.created_at.strftime("%d/%m/%Y")%></td>            
      <th><%=Gym.find(token.gym_id).name%></th>  
    <%end%>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/tokens/edit.html.erb
<h2>Validação de Tokens</h2>


<%= render 'form', token: @token %>

app/views/tokens/index.html.erb
<p id="notice"><%= notice %></p>

<%if current_user.regular? %>
   <%= render partial: 'regular_user_index', token: @token %>
<%elsif current_user.gympass?%>
  <h2>Validação de Token</h2>
  <%= render partial: 'gympass_index', token: @token %>   
<%else%>
  <h2>Validação de Token</h2>
  <%= render partial: 'admin_index', token: @token %>   
<%end%>

app/views/tokens/new.html.erb
<h1>Editing Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @token.status %>
</p>