config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users,  :has_many => :addresses, :controllers => {registrations: 'registrations'}

  resources :users do
  	resources :addresses
  end
  
  resources :tokens 
    
  resources :gyms do
  	resources :addresses
  end
    
    #resources :requests, defaults: { format: 'json' }
    get 'home/index' => 'home#index'

    root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gym.rb
class Gym < ApplicationRecord
  belongs_to :user
  belongs_to :token
  has_one :address , as: :addressable, :dependent => :destroy
  
  accepts_nested_attributes_for :address

  	validates :name, presence: true, uniqueness:true
	validates :opening_time, presence: true
	validates :closing_time, presence: true
	validates :user_id, presence: true

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController

  before_action :set_gym, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! #except: [:index]
  
  # GET /gyms
  # GET /gyms.json
  def index
    if current_user.admin?
      @gyms = Gym.all.select{ |g| g.user_id == current_user.id }
    elsif current_user.gympass?
      @gyms = Gym.all
    end
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
    @user = User.find(current_user.id)
    if  @user.regular?
        flash[:notice] = "Usuário sem permissão para executar a ação"
        redirect_to :controller => 'home'
    end
  end

  # GET /gyms/new
  def new
    if current_user.admin? || current_user.gympass? 
      @gym = Gym.new
      @gym.build_address
    else
      flash[:alert] = "Usuário sem permissão para executar a ação"
      redirect_to(request.referrer || root_path)
    end
  end

  # GET /gyms/1/edit
  def edit
    @user = User.find(current_user.id)
    if  @user.regular?
        flash[:notice] = "Usuário sem permissão para executar a ação"
        redirect_to :controller => 'home'
    end
  end

  # POST /gyms
  # POST /gyms.json
  def create
    
    if current_user.admin? || current_user.gympass? 
      @gym = Gym.new(gym_params)
      @gym.user_id = current_user.id
      @gym.status = false
      @gym.address.types = 1
      respond_to do |format|
        if @gym.save
          #@gym.create_address
          @users = User.all
          ConfirmationMailer.confirmation_email(@gym, @users).deliver_now
              
          format.html { redirect_to @gym, notice: 'Academia cadastrada com sucesso.' }
          format.json { render :show, status: :created, location: @gym }
        else
          format.html { render :new }
          format.json { render json: @gym.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:alert] = "Usuário sem permissão para executar a ação"
      redirect_to(request.referrer || root_path)
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    @user = User.find(current_user.id)
    if  @gym.user_id == @user.id || @user.gympass?
      respond_to do |format|
        if @gym.update(gym_params)
          format.html { redirect_to @gym, notice: 'Academia atualizada com sucesso.' }
          format.json { render :show, status: :ok, location: @gym }
        else
          format.html { render :edit }
          format.json { render json: @gym.errors, status: :unprocessable_entity }
        end
      end
    else
        flash[:notice] = "Usuário sem permissão para executar a ação"
        redirect_to :controller => 'home'
    end
    
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @user = User.find(current_user.id)
    if  @gym.user_id == @user.id || @user.gympass?
        @gym.destroy
        respond_to do |format|
          format.html { redirect_to gyms_url, notice: 'Academia deletada com sucesso' }
          format.json { head :no_content }
        end
    else
      flash[:alert] = "Usuário sem permissão para executar a ação"
      redirect_to(request.referrer || root_path)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_params
        params.require(:gym).permit!
    end

end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<script type="text/javascript">
  addressMap('gym', 0);

  function formatAddress(){
    var street  = document.getElementById('gym_address_attributes_street').value;
    var city  = document.getElementById('gym_address_attributes_city').value;
    var state  = document.getElementById('gym_address_attributes_state').value;
    var zip_code  = document.getElementById('gym_address_attributes_zip_code').value;
    var address = street +','+city+','+state+','+zip_code;

    geocode(address, 'gym', 0);
  }
</script>

<%@hidden = 'display:none'%>
<%= form_for(gym) do |f| %>
  <% if gym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
      <% gym.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :opening_time, "Abertura" %>
    <%= f.time_select :opening_time %>
  </div>

  <div class="field">
    <%= f.label :closing_time, "Fechamento" %>
    <%= f.time_select :closing_time %>
  </div>
   <br><br>
  <h2>Endereços</h2>
  <em>Informe um endereço ou indique uma localização no mapa</em>
  <br>
    
  <%= f.fields_for :address do |a| %>
    <br>
  <div style="width:40%; height:300px; float:left;" >
     <div class="field">
      <div>
        <%= a.label :street, "Rua" %>  
      </div>
      <div>
        <%= a.text_field :street %>  
      </div>
    </div>

    <div class="field">
      <div>
        <%= a.label :zip_code, "Cep" %>    
      </div>
      <div>
        <%= a.text_field :zip_code %>    
      </div>
    </div>
    
   <div class="field">
      <div>
        <%= a.label :city, "Cidade" %>  
      </div>
      <div>
        <%= a.text_field :city %>  
      </div>
    </div>

    <div class="field">
      <div>
        <%= a.label :state, "Estado" %>  
      </div>
      <div>
        <%= a.text_field :state, :onchange => "formatAddress();"%>  
      </div>
    </div>
    <div class="field">
       <div>
          <%= a.label :latitude, "Latitude" %>  
        </div>
        <div>
          <%= a.text_field :latitude %>  
        </div>
      </div>
       <div class="field">
        <div>
          <%= a.label :longitude, "Longitude" %>  
        </div>
        <div>
          <%= a.text_field :longitude %>  
        </div>
      </div>
    </div>
    <div id="map-canvas" style="width:60%; height:300px; float:left;"></div>
  <br>
  <% end %> 
  <%if current_user.gympass? %>
     <div class="field">
      <h2> <%= f.label :status, "Aprovar?" %> </h2> 
      <%= f.radio_button :status, true, :style => "float:left"%>
    </div>
  <%end%>
  <br><br>
  
  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/gyms/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing Gym</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Show', @gym %> |
<%= link_to 'Back', gyms_path %>

app/views/gyms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Academias Administradas</h1>

<%if @gyms.empty? %>
    <h2>Você ainda não possui academias </h2>
<%else%>  
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Abertura</th>
        <th>Fechamento</th>
        <th>Administrador</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @gyms.each do |gym| %>
        <tr>
          <td><%= gym.name %></td>
          <td><%= (gym.opening_time).to_s(:time) %></td>
          <td><%= (gym.closing_time).to_s(:time) %></td>
          <td><%= User.find(gym.user_id).name%>
          <%if gym.status? %>
            <td>Aprovada<td>
          <%else%>
            <td>Aguardando Aprovação<td>
          <%end%>
          <td><%= link_to 'Exibir', gym %></td>
          <td><%= link_to 'Editar', edit_gym_path(gym) %></td>
          <td><%= link_to 'Deletar', gym, method: :delete, data: { confirm: 'Confirmar?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%
  end
%>
<br>

<%= button_to 'Cadastrar Nova Academia', new_gym_path, :method => "get" %>

app/views/gyms/new.html.erb
<p id="notice"><%= notice %></p>
<h1>Cadastro de Academias</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Voltar', gyms_path %>

app/views/gyms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @gym.name %>
</p>

<p>
  <strong>Abertura:</strong>
  <%= (@gym.opening_time).to_s(:time) %>
</p>

<p>
  <strong>Fechamento:</strong>
  <%= (@gym.closing_time).to_s(:time) %>
</p>

<p>
  <strong>Administrador:</strong>
  <%= @gym.user.name %>
</p>
<%= link_to 'Editar', edit_gym_path(@gym) %> |
<%= link_to 'Voltar', gyms_path %>